spring:
  #服务名称
  application:
    name: nacos-provider
  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #数据库连接池
  datasource:
    druid:
      username: root
      password: 111111
      url: jdbc:mysql://127.0.0.1:3306/myshop?useUnicode=true&characterEncoding=utf8
      initial-size: 10
      max-active: 50
      validation-query: select 1
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
  #redis配置
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    sentinel:
      master: mymaster
      nodes: 172.16.8.101:26379, 172.16.8.101:26380, 172.16.8.101:26381
  #MQ配置
  rabbitmq:
    addresses: 172.16.8.101:5672
    connection-timeout: 15000
    listener:
      order:
        exchange:
          durable: true
          ignoreDeclarationExceptions: true
          name: exchange-2
          type: topic
        key: springboot.*
        queue:
          durable: true
          name: queue-2
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
    password: guest
    username: guest
    virtual-host: /

server:
  port: 8081

#端点检查
management:
  endpoints:
    web:
      exposure:
        include: "*"

##mybatis配置
mybatis:
  type-aliases-package: com.zlm.hello.spring.cloud.alibaba.nacos.provider.model
  mapper-locations: classpath:mapper/*Mapper*.xml
  configuration:
    cache-enabled: true
logging:
  level:
   com.zlm.hello.spring.cloud.alibaba.nacos.provider.dao : debug

kaptcha:
  #是否有边框，默认为yes，可选yes、no
  border: "yes"
  #边框颜色
  border.color: 105,179,90
  textproducer:
    font:
      #验证码字体颜色
      color: blue
      #文本字符大小
      size: 30
      #文本字体样式
      names: 宋体,楷体,微软雅黑
    char:
      #验证码文本字符长度
      length: 4
  image:
    #图片宽度
    width: 120
    #图片高度
    height: 40
  #session:
    #存储session key
    #key: code
async:
  core_pool_size: 50
  max_pool_size: 50
  queue_capacity: 20
  keep_alive_seconds: 10
  await_termination_seconds: 3