host:
  ip:
    mongodb: 172.16.0.41
    nacos: 127.0.0.1
database-name:
  mongodb: ralph

spring:
  #服务名称
  application:
    name: nacos-provider3
  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: ${host.ip.nacos}:8848,



server:
  port: 8083

#端点检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
