host:
  ip:
    mongodb: 192.168.2.101
spring:
  #服务名称
  application:
    name: nacos-provider3
  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



server:
  port: 8083

#端点检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
